Update README.md to include missing module
When running the example listed in the README.md, I'm getting the following error:

```ocaml
Error: Unbound value ->!
```

If I open `Caqti_request.Infix` the error goes away.